# Generated by Django 5.2.5 on 2025-09-13 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_teacher_allowances_teacher_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
