# Generated by Django 6.1.1 on 2026-09-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_staff_department_staff_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
